version: "3.8"

volumes:
  base-data:

services:

  db:
    restart: unless-stopped
    image: tivix/docker-postgres
    env_file:
      - ./django_web/.env

  web:
    restart: unless-stopped
    env_file:
      - ./django_web/.env
    build:
      context: ./django_web
      target: dev
      dockerfile: ./Dockerfile
      args:
        requirements_file: "base.txt"
    ports:
      - "8010:8000"
      - "8080:8080"
    command: bash -c "waitforit -host=db -port=5432 --timeout 30 &&
          python3 /code/manage.py collectstatic --noinput &&
          python3 /code/manage.py migrate &&
          python3 /code/manage.py initadmin &&
          echo "running" && tail -f /dev/null"
    depends_on:
      - db
    volumes:
      - ./django_web/:/code
